---
env:
    name: dmc_walker_walk
    n_envs: 1
    frame_skip: 2
    precision: &prec 16

model:
    encoder:
        has_cnn: True
    rssm:
        stoch_size: 30
        deter_size: 200
        hidden_size: 200
        activation: elu
    reward:
        units_list: [400, 400]
        activation: elu
    decoder:
        has_cnn: True
    actor:
        units_list: [400, 400, 400, 400]
        activation: elu
        init_std: 5
        min_std: 1e-4
        mean_scale: 5
    value:
        units_list: [400, 400, 400]
        activation: elu
    # uncomment the following code for games with terminal steps
    # discount:
    #     units_list: [400, 400, 400]
    #     activation: elu
agent:
    algorithm: &algo dreamer
    batch_size: &bs 50
    precision: *prec

    store_state: False
    burn_in: False
    sample_size: &ss 50
    burn_in_size: 0

    additional_rnn_inputs:
        prev_action: float16

    MAX_STEPS: 5e6
    LOG_PERIOD: 1000
    EVAL_PERIOD: 10000
    TRAIN_PERIOD: 1000
    N_UPDATES: 100
    log_images: True

    # model
    free_nats: 3.
    kl_scale: 1.
    discount_scale: 10.
    # behavior
    horizon: 15
    gamma: &gamma 0.99
    lambda: .95
    act_eps: .3

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    RECORD: True

    # arguments for optimizer
    opt_name: adam
    clip_norm: 100.
    weight_decay: 0.
    model_lr: 6e-4
    actor_lr: 8e-5
    value_lr: 8e-5

buffer:
    replay_type: episodic                      # per or uniform

    # arguments for general replay
    batch_size: *bs
    sample_size: *ss
    max_episodes: 800
    min_episodes: 5
    save: False
