---
env:
    name: procgen_coinrun
    distribution_mode: easy
    frame_skip: 1
    n_envs: &ne 64
    frame_stack: 1
    np_obs: True
    reward_scale: 1
    reward_clip: 10

model:
    encoder:
        cnn_name: impala
    q:
        units_list: [512]
        layer_type: dense
        kernel_initializer: glorot_uniform
        activation: relu
        duel: False
        stoch_action: True
        tau: &tau 0.01

agent:
    algorithm: &algo dqn
    replay_type: &replay per
    gamma: &gamma .99
    precision: &prec 32
    batch_size: &bs 64
    n_steps: &nsteps 3      # n-step target

    MUNCHAUSEN: False   # whether to use munchausen rl target
    probabilistic_regularization: null

    tau: *tau
    alpha: .9
    clip_logpi_min: -1

    schedule_act_eps: True
    act_eps_type: apex
    act_eps: .3
    eval_act_eps: 0
    schedule_act_temp: True
    n_exploit_envs: 8
    min_temp: .5
    max_temp: 10
    eval_act_temp: .5

    MAX_STEPS: 1e7
    TRAIN_PERIOD: 256
    EVAL_PERIOD: 2.5e5
    LOG_PERIOD: 2.5e5
    N_UPDATES: 24
    RECORD: True
    N_EVAL_EPISODES: 200

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: huber
    target_update_period: 1500  # trainning step
    tbo: False                              # transformed Bellman Operator
    
    # arguments for optimizer
    opt_name: adam
    schedule_lr: False
    lr: 2.5e-4
    clip_norm: 0
    opt_kwargs:
        epsilon: 1.5e-4

    # arguments for PER
    per_alpha: .6
    per_epsilon: 1.e-4
    use_is_ratio: &is False

buffer:
    replay_type: *replay
    seqlen: 10
    n_envs: *ne
    # arguments for PER
    beta0: .4
    beta_steps: 1e6
    to_update_top_priority: True
    use_is_ratio: *is

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: *bs
    min_size: 1600
    capacity: 2.5e5
    has_next_obs: True
