---
algorithm: &algo ppo

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be reset in our training process
root_dir: *algo
model_name: *algo

env:
    name: &env_name BipedalWalker-v3
    n_workers: 1
    n_envs: &nenvs 64
    seed: 0
    reward_min: -1
    reward_max: null

agent:
    algorithm: *algo
    precision: 32

    MAX_STEPS: 1e10
    N_STEPS: &nsteps 256
    LOG_PERIOD: 200
    EVAL_PERIOD: 200

    RECORD_VIDEO: False
    N_EVAL_EPISODES: 1

strategy:
    train_loop:
        N_EPOCHS: &nepochs 4
        N_VALUE_EPOCHS: &nval_epochs 0
        N_MBS: &nmbs 4
        max_kl: 0            # early stop when max_kl is violated. 0 or null suggests unbound

        # (once, reuse, null)
        # "once" updates values at the end of each epoch
        # "reuse" updates values using value from train, which is staler than once
        # null doesn't update values.
        value_update: null

model:
    encoder: 
        nn_id: null
        units_list: []
        activation: relu
    policy:
        nn_id: policy
        units_list: [256, 256]
        init_std: 1
        norm: null
        kernel_initializer: orthogonal
        activation: tanh
    value:
        nn_id: value
        units_list: [256, 256]
        norm: null
        kernel_initializer: orthogonal
        activation: tanh

loss:
    # arguments for loss
    value_loss: clip
    clip_range: .2          # clip range for ppo
    entropy_coef: 1e-3
    value_coef: 1

trainer:
    optimizer:
        opt_name: adam
        schedule_lr: False
        lr: 2e-4
        clip_norm: .5
        epsilon: 1.e-5

actor:
    rms:
        normalize_obs: True
        normalize_reward: True
        gamma: &gamma .99

buffer:
    use_dataset: True

    adv_type: gae     # nae or gae
    gamma: *gamma
    lam: .95
    n_envs: *nenvs
    N_STEPS: *nsteps
    N_EPOCHS: *nepochs
    N_VALUE_EPOCHS: *nval_epochs
    N_MBS: *nmbs        # number of minibatches
    norm_adv: minibatch
    sample_keys: [obs, action, value, traj_ret, advantage, logpi]
    # mini-batch size = n_workers * n_envs * epslen / n_mbs
