---
# NOTE: root_dir and model_name will be specified to all configs in run.train.py
algorithm: &algo ppo

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be reset in our training process
root_dir: *algo
model_name: *algo

env:
    name: &env_name procgen_coinrun
    n_workers: 1
    n_envs: &nenvs 64
    frame_skip: 1
    frame_stack: 1
    # num_levels: 200
    distribution_mode: easy

agent:
    algorithm: *algo
    precision: 16

    MAX_STEPS: 1e10
    N_STEPS: &nsteps 256
    LOG_PERIOD: 200
    EVAL_PERIOD: 200

    RECORD_VIDEO: True
    N_EVAL_EPISODES: 1

strategy:
    train_loop:
        N_EPOCHS: &nepochs 4
        N_VALUE_EPOCHS: &nval_epochs 0
        N_MBS: &nmbs 4
        max_kl: 0            # early stop when max_kl is violated. 0 or null suggests unbound

        # (once, reuse, null)
        # "once" updates values at the end of each epoch
        # "reuse" updates values using value from train, which is staler than once
        # null doesn't update values.
        value_update: null

    RECORD_VIDEO: True

model:
    encoder: 
        nn_id: cnn_impala
        out_size: 256
    policy:
        nn_id: policy
        units_list: []
        norm: null
        kernel_initializer: orthogonal
        activation: relu
        eval_act_temp: 1
    value:
        nn_id: value
        units_list: []
        norm: null
        kernel_initializer: orthogonal
        activation: relu

loss:
    # arguments for loss
    value_loss: clip
    clip_range: .2          # clip range for ppo
    entropy_coef: .01
    value_coef: .5

trainer:
    optimizer:
        opt_name: adam
        schedule_lr: False
        lr: 5e-4
        clip_norm: .5
        epsilon: 1.e-5

actor:
    rms:
        normalize_obs: False
        normalize_reward: True
        gamma: &gamma .999

buffer:
    use_dataset: True

    adv_type: gae     # nae or gae
    gamma: *gamma
    lam: .95
    n_envs: *nenvs
    N_STEPS: *nsteps
    N_EPOCHS: *nepochs
    N_VALUE_EPOCHS: *nval_epochs
    N_MBS: *nmbs        # number of minibatches
    norm_adv: minibatch
    sample_keys: [obs, action, value, traj_ret, advantage, logpi]
    # mini-batch size = n_workers * n_envs * epslen / n_mbs
